spring.application.name=risk-service
server.port=8083

# MongoDB
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/paymentdb}
spring.data.mongodb.database=paymentdb

# Python ML API (your existing LSTM anomaly detection FastAPI)
python.ml.api.url=${PYTHON_ML_API_URL:http://localhost:8000}

# Logging
logging.level.com.madhumitha=INFO
