spring.application.name=transaction-service
server.port=8082

# MongoDB
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/paymentdb}
spring.data.mongodb.database=paymentdb

# Risk service URL
risk.service.url=${RISK_SERVICE_URL:http://risk-service:8083}

# Logging
logging.level.com.madhumitha=INFO
