spring.application.name=user-service
server.port=8081

# MongoDB
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/paymentdb}
spring.data.mongodb.database=paymentdb

# Logging
logging.level.com.madhumitha=INFO
logging.level.org.springframework.data.mongodb=INFO
